cabinet/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :docs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

cabinet/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cabinet/app/models/doc.rb
class Doc < ApplicationRecord
end

cabinet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

cabinet/app/controllers/docs_controller.rb
class DocsController < ApplicationController

    before_action :find_doc, only:[:show, :edit, :update, :destroy ]

    def index
        @docs = Doc.all.order("created_at DESC")
    end

    def show
    end

    def new
        @doc = Doc.new
    end

    def create
        @doc = Doc.new(doc_params)

        if @doc.save
            redirect_to @doc
        else
            render 'new'
        end
    end

    def edit

    end

    def update
        if @doc.update(doc_params)
             redirect_to @doc
         else
             render 'edit'
         end
    end

    def destroy
        if @doc.destroy()
            redirect_to docs_path
        end
    end

    private

        def find_doc
            @doc = Doc.find(params[:id])
        end

        def doc_params
            params.require(:doc).permit(:title, :content)
        end
end

cabinet/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

cabinet/app/helpers/application_helper.rb
module ApplicationHelper
end

cabinet/app/helpers/docs_helper.rb
module DocsHelper
end

cabinet/app/helpers/welcome_helper.rb
module WelcomeHelper
end

cabinet/app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
    = f.input :title
    = f.input :content
    = f.button :submit

cabinet/app/views/docs/edit.html.haml
%h1 Fix Doc!

.body
    = render 'form'

cabinet/app/views/docs/index.html.haml
- @docs.each do |doc|
    %h2= link_to doc.title, doc
    %p= time_ago_in_words(doc.created_at)
    %p= truncate(doc.content, lenght:50)

= link_to "Create Doc", new_doc_path

cabinet/app/views/docs/new.html.haml
%h1 New Doc

.body
    = render 'form'

cabinet/app/views/docs/show.html.haml
%h1= @doc.title
%p= @doc.content

= link_to "All docs", docs_path
= link_to "Fix Doc", edit_doc_path
= link_to "Delete doc", doc_path(@doc), method: :delete,
                  data: {confirm: "Are you sure"}

cabinet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cabinet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

cabinet/app/views/welcome/index.html.haml
%h1 HELLO